### ISSUE TITLE
Snackbar Wrapper Layout 변경에 대한 제의

### ISSUE THREAD

**Issue by l2hyunwoo** [jinsu4755/SOPT28_AdditionalExample#1]
> Snackbar will walk up the view tree trying to find a suitable parent, which is defined as a CoordinatorLayout or the window 
> decor's content view, whichever comes first.

``Snackbar``는 CoordinatorLayout 내부에 있어야 상대적인 위치 조절이 가능하고 Dismiss, Swipe에 자유롭게 반응할 수 있다고 함. 이 점 참고해서 Snackbar practice 조금 바꿀 수 있나?

출처: https://developer.android.com/reference/com/google/android/material/snackbar/Snackbar

**Comment by jinsu4755** [comment]
해당 부분은 이미 인지하고 있는 부분이고 해당 레포지터리는 기획이후 미완성단계이나 솝커톤에서 예시사용을 위해 공개한 레포라 아직 미완성 프로젝트도 있음! -> 내부 리드미 없으면 미완성임.

해당 예시 프로젝트의 경우 초기 기획이 SnackBar를 세미나에서 다루지 않기 때문에 이런 것도 있다는 예시를 보여주기 위한 딱 기본 기능만 보여주기 위함이었음. 

공식 문서 가이드에도 나온 이야기지만 `SnackBar`는 기본적인 레이아웃 객체에서 기본적인 기능을 제공하고
여기에 CoordinatorLayout을 사용하면 추가적으로
스와이프로 dissmiss, 상대적 위치 조절 기능을 제공함.

> A Snackbar is attached to a view. The Snackbar provides basic functionality if it is attached to any object derived from the View class, such as any of the common layout objects. However, if the Snackbar is attached to a CoordinatorLayout, the Snackbar gains additional features:
> - The user can dismiss the Snackbar by swiping it away.
> - The layout moves some other UI elements when the Snackbar appears. For example, if the layout has a FloatingActionButton, the layout moves the button up when it shows a Snackbar, instead of drawing the Snackbar on top of the button. You can see how this looks in Figure 1.

또한 위 부분은 README 설명으로 포함될 예정이었음.

기본 기능이외 스와이프나 플로팅 버튼처럼 뭔가 이동시킬 계획이 없어서 해당 부분을 사용할 일이 없기에 CoordinatorLayout을 사용하지 않았는데

일단 추가를 고려해보겠음!
